name: CD

on:
  push:
    branches: ['master']

jobs:
  nodejs:
    name: docsify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7.23.0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: pnpm

      - name: Install Packages
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run dev:lint:ci

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.SFTP_USERNAME }}'
          server: '${{ secrets.SFTP_SERVER }}'
          port: '${{ secrets.SFTP_PORT }}'
          ssh_private_key: ${{ secrets.SFTP_PRIVKEY }} 
          local_path: './dist/*'
          remote_path: '/var/www/wiki.banablock.net'
          args: '-o ConnectTimeout=5'
